version: '3.8'
services:
  gateway:
    build: gateway/
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    env_file:
      - .env

  server:
    build: server/
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13.7-alpine
    container_name: shareit-db
    ports:
      - "5432:5432"
    env_file:
      - .env