version: ''
services:
  gateway:
    build: gateway/
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server

    # TO-DO в реальных проектах не выкладывать учётные данные, а поместить их в файл
    # В рамках Shareit github не даёт это сделать, т.к. у него нет файла
    # env_file:
    #   - .env
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server/
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    # TO-DO в реальных проектах не выкладывать учётные данные, а поместить их в файл
    # В рамках Shareit github не даёт это сделать, т.к. у него нет файла
    # env_file:
    #   - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: postgres:13.7-alpine
    container_name: shareit-db
    ports:
      - "5432:5432"
    # TO-DO в реальных проектах не выкладывать учётные данные, а поместить их в файл
    # В рамках Shareit github не даёт это сделать, т.к. у него нет файла
    # env_file:
    #   - .env
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root